package com.example.rabbit.mulltiplerabbit.protobuff;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto

public final class Rpc {
  private Rpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RpcMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RpcMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    long getId();

    /**
     * <code>.RpcMessage.Result result = 2;</code>
     * @return The enum numeric value on the wire for result.
     */
    int getResultValue();
    /**
     * <code>.RpcMessage.Result result = 2;</code>
     * @return The result.
     */
    RpcMessage.Result getResult();

    /**
     * <code>string version = 3;</code>
     * @return The version.
     */
    String getVersion();
    /**
     * <code>string version = 3;</code>
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>string service = 4;</code>
     * @return The service.
     */
    String getService();
    /**
     * <code>string service = 4;</code>
     * @return The bytes for service.
     */
    com.google.protobuf.ByteString
        getServiceBytes();

    /**
     * <code>.RpcMessage.Source source = 5;</code>
     * @return The enum numeric value on the wire for source.
     */
    int getSourceValue();
    /**
     * <code>.RpcMessage.Source source = 5;</code>
     * @return The source.
     */
    RpcMessage.Source getSource();

    /**
     * <code>int64 context_id = 6;</code>
     * @return The contextId.
     */
    long getContextId();

    /**
     * <code>bytes payload_data = 7;</code>
     * @return The payloadData.
     */
    com.google.protobuf.ByteString getPayloadData();

    /**
     * <code>.RpcMessage.Payload payload_class = 8;</code>
     * @return The enum numeric value on the wire for payloadClass.
     */
    int getPayloadClassValue();
    /**
     * <code>.RpcMessage.Payload payload_class = 8;</code>
     * @return The payloadClass.
     */
    RpcMessage.Payload getPayloadClass();

    /**
     * <code>bool compress = 10;</code>
     * @return The compress.
     */
    boolean getCompress();

    /**
     * <code>int64 paging = 11;</code>
     * @return The paging.
     */
    long getPaging();

    /**
     * <code>int64 limit = 12;</code>
     * @return The limit.
     */
    long getLimit();
  }
  /**
   * Protobuf type {@code RpcMessage}
   */
  public static final class RpcMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RpcMessage)
      RpcMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RpcMessage.newBuilder() to construct.
    private RpcMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RpcMessage() {
      result_ = 0;
      version_ = "";
      service_ = "";
      source_ = 0;
      payloadData_ = com.google.protobuf.ByteString.EMPTY;
      payloadClass_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RpcMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RpcMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              result_ = rawValue;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              service_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              source_ = rawValue;
              break;
            }
            case 48: {

              contextId_ = input.readInt64();
              break;
            }
            case 58: {

              payloadData_ = input.readBytes();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              payloadClass_ = rawValue;
              break;
            }
            case 80: {

              compress_ = input.readBool();
              break;
            }
            case 88: {

              paging_ = input.readInt64();
              break;
            }
            case 96: {

              limit_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Rpc.internal_static_RpcMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Rpc.internal_static_RpcMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RpcMessage.class, Builder.class);
    }

    /**
     * <pre>
     *Enum
     * </pre>
     *
     * Protobuf enum {@code RpcMessage.Result}
     */
    public enum Result
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RESULT_NONE = 0;</code>
       */
      RESULT_NONE(0),
      /**
       * <code>INVALID_VERSION = 2;</code>
       */
      INVALID_VERSION(2),
      /**
       * <code>INVALID_SERVICE = 3;</code>
       */
      INVALID_SERVICE(3),
      /**
       * <code>INVALID_PAYLOAD = 4;</code>
       */
      INVALID_PAYLOAD(4),
      /**
       * <code>NOT_AUTHENTICATED = 5;</code>
       */
      NOT_AUTHENTICATED(5),
      /**
       * <code>SERVICE_TIMEOUT = 6;</code>
       */
      SERVICE_TIMEOUT(6),
      /**
       * <code>SERVICE_REJECTED = 7;</code>
       */
      SERVICE_REJECTED(7),
      /**
       * <code>SERVICE_UNAVAILABLE = 8;</code>
       */
      SERVICE_UNAVAILABLE(8),
      /**
       * <code>REQUIRE_VPN = 9;</code>
       */
      REQUIRE_VPN(9),
      /**
       * <code>MAINTAINANCE = 10;</code>
       */
      MAINTAINANCE(10),
      /**
       * <code>INTERNAL_ERROR = 99;</code>
       */
      INTERNAL_ERROR(99),
      /**
       * <code>SUCCESS = 100;</code>
       */
      SUCCESS(100),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RESULT_NONE = 0;</code>
       */
      public static final int RESULT_NONE_VALUE = 0;
      /**
       * <code>INVALID_VERSION = 2;</code>
       */
      public static final int INVALID_VERSION_VALUE = 2;
      /**
       * <code>INVALID_SERVICE = 3;</code>
       */
      public static final int INVALID_SERVICE_VALUE = 3;
      /**
       * <code>INVALID_PAYLOAD = 4;</code>
       */
      public static final int INVALID_PAYLOAD_VALUE = 4;
      /**
       * <code>NOT_AUTHENTICATED = 5;</code>
       */
      public static final int NOT_AUTHENTICATED_VALUE = 5;
      /**
       * <code>SERVICE_TIMEOUT = 6;</code>
       */
      public static final int SERVICE_TIMEOUT_VALUE = 6;
      /**
       * <code>SERVICE_REJECTED = 7;</code>
       */
      public static final int SERVICE_REJECTED_VALUE = 7;
      /**
       * <code>SERVICE_UNAVAILABLE = 8;</code>
       */
      public static final int SERVICE_UNAVAILABLE_VALUE = 8;
      /**
       * <code>REQUIRE_VPN = 9;</code>
       */
      public static final int REQUIRE_VPN_VALUE = 9;
      /**
       * <code>MAINTAINANCE = 10;</code>
       */
      public static final int MAINTAINANCE_VALUE = 10;
      /**
       * <code>INTERNAL_ERROR = 99;</code>
       */
      public static final int INTERNAL_ERROR_VALUE = 99;
      /**
       * <code>SUCCESS = 100;</code>
       */
      public static final int SUCCESS_VALUE = 100;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Result valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Result forNumber(int value) {
        switch (value) {
          case 0: return RESULT_NONE;
          case 2: return INVALID_VERSION;
          case 3: return INVALID_SERVICE;
          case 4: return INVALID_PAYLOAD;
          case 5: return NOT_AUTHENTICATED;
          case 6: return SERVICE_TIMEOUT;
          case 7: return SERVICE_REJECTED;
          case 8: return SERVICE_UNAVAILABLE;
          case 9: return REQUIRE_VPN;
          case 10: return MAINTAINANCE;
          case 99: return INTERNAL_ERROR;
          case 100: return SUCCESS;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Result>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Result> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Result>() {
              public Result findValueByNumber(int number) {
                return Result.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RpcMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Result[] VALUES = values();

      public static Result valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Result(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RpcMessage.Result)
    }

    /**
     * Protobuf enum {@code RpcMessage.Source}
     */
    public enum Source
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>SOURCE_NONE = 0;</code>
       */
      SOURCE_NONE(0),
      /**
       * <code>IOS = 1;</code>
       */
      IOS(1),
      /**
       * <code>ANDROID = 2;</code>
       */
      ANDROID(2),
      /**
       * <code>External = 9;</code>
       */
      External(9),
      /**
       * <code>WEB = 10;</code>
       */
      WEB(10),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>SOURCE_NONE = 0;</code>
       */
      public static final int SOURCE_NONE_VALUE = 0;
      /**
       * <code>IOS = 1;</code>
       */
      public static final int IOS_VALUE = 1;
      /**
       * <code>ANDROID = 2;</code>
       */
      public static final int ANDROID_VALUE = 2;
      /**
       * <code>External = 9;</code>
       */
      public static final int External_VALUE = 9;
      /**
       * <code>WEB = 10;</code>
       */
      public static final int WEB_VALUE = 10;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Source valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Source forNumber(int value) {
        switch (value) {
          case 0: return SOURCE_NONE;
          case 1: return IOS;
          case 2: return ANDROID;
          case 9: return External;
          case 10: return WEB;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Source>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Source> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Source>() {
              public Source findValueByNumber(int number) {
                return Source.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RpcMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final Source[] VALUES = values();

      public static Source valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Source(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RpcMessage.Source)
    }

    /**
     * Protobuf enum {@code RpcMessage.Payload}
     */
    public enum Payload
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *Common message (0~19)
       * </pre>
       *
       * <code>PAYLOAD_NONE = 0;</code>
       */
      PAYLOAD_NONE(0),
      /**
       * <code>AUTHEN_REQ = 1;</code>
       */
      AUTHEN_REQ(1),
      /**
       * <code>HEARTBEAT_REQ = 2;</code>
       */
      HEARTBEAT_REQ(2),
      /**
       * <code>LOGIN_REQ = 3;</code>
       */
      LOGIN_REQ(3),
      /**
       * <code>AUTHEN_RES = 11;</code>
       */
      AUTHEN_RES(11),
      /**
       * <code>HEARTBEAT_RES = 12;</code>
       */
      HEARTBEAT_RES(12),
      /**
       * <code>LOGIN_RES = 13;</code>
       */
      LOGIN_RES(13),
      /**
       * <pre>
       *Pricing message (20~59)
       * </pre>
       *
       * <code>LAST_QUOTE_REQ = 20;</code>
       */
      LAST_QUOTE_REQ(20),
      /**
       * <code>SUBSCRIBE_QUOTE_REQ = 21;</code>
       */
      SUBSCRIBE_QUOTE_REQ(21),
      /**
       * <code>UNSUBSCRIBE_QUOTE_REQ = 22;</code>
       */
      UNSUBSCRIBE_QUOTE_REQ(22),
      /**
       * <code>CHART_REQ = 23;</code>
       */
      CHART_REQ(23),
      /**
       * <pre>
       *notify new quote to client
       * </pre>
       *
       * <code>QUOTE_EVENT = 29;</code>
       */
      QUOTE_EVENT(29),
      /**
       * <code>LAST_QUOTE_RES = 30;</code>
       */
      LAST_QUOTE_RES(30),
      /**
       * <code>SUBSCRIBE_QUOTE_RES = 31;</code>
       */
      SUBSCRIBE_QUOTE_RES(31),
      /**
       * <code>UNSUBSCRIBE_QUOTE_RES = 32;</code>
       */
      UNSUBSCRIBE_QUOTE_RES(32),
      /**
       * <code>CHART_RES = 33;</code>
       */
      CHART_RES(33),
      /**
       * <pre>
       *Trading messasge (60~99)
       * </pre>
       *
       * <code>NEW_ORDER_SINGLE_REQ = 60;</code>
       */
      NEW_ORDER_SINGLE_REQ(60),
      /**
       * <code>NEW_ORDER_MULTI_REQ = 61;</code>
       */
      NEW_ORDER_MULTI_REQ(61),
      /**
       * <code>CLOSE_ORDER_REQ = 62;</code>
       */
      CLOSE_ORDER_REQ(62),
      /**
       * <code>MODIFY_ORDER_REQ = 63;</code>
       */
      MODIFY_ORDER_REQ(63),
      /**
       * <code>CANCEL_ORDER_REQ = 64;</code>
       */
      CANCEL_ORDER_REQ(64),
      /**
       * <code>TRIGGERED_STOP_ORDER_REQ = 65;</code>
       */
      TRIGGERED_STOP_ORDER_REQ(65),
      /**
       * <pre>
       *notify position changed
       * </pre>
       *
       * <code>ORDER_EVENT = 68;</code>
       */
      ORDER_EVENT(68),
      /**
       * <code>NEW_ORDER_SINGLE_RES = 70;</code>
       */
      NEW_ORDER_SINGLE_RES(70),
      /**
       * <code>NEW_ORDER_MULTI_RES = 71;</code>
       */
      NEW_ORDER_MULTI_RES(71),
      /**
       * <code>CLOSE_ORDER_RES = 72;</code>
       */
      CLOSE_ORDER_RES(72),
      /**
       * <code>MODIFY_ORDER_RES = 73;</code>
       */
      MODIFY_ORDER_RES(73),
      /**
       * <code>CANCEL_ORDER_RES = 74;</code>
       */
      CANCEL_ORDER_RES(74),
      /**
       * <code>TRIGGERED_STOP_ORDER_RES = 75;</code>
       */
      TRIGGERED_STOP_ORDER_RES(75),
      /**
       * <pre>
       *Account
       * </pre>
       *
       * <code>BALANCE_UPDATE_REQ = 80;</code>
       */
      BALANCE_UPDATE_REQ(80),
      /**
       * <code>ACCOUNT_CREATE_REQ = 81;</code>
       */
      ACCOUNT_CREATE_REQ(81),
      /**
       * <code>ACCOUNT_UPDATE_REQ = 82;</code>
       */
      ACCOUNT_UPDATE_REQ(82),
      /**
       * <code>ACCOUNT_DETAIL_REQ = 83;</code>
       */
      ACCOUNT_DETAIL_REQ(83),
      /**
       * <code>ACCOUNT_CREATE_MULTI_REQ = 84;</code>
       */
      ACCOUNT_CREATE_MULTI_REQ(84),
      /**
       * <code>ACCOUNT_BALANCE_REQ = 85;</code>
       */
      ACCOUNT_BALANCE_REQ(85),
      /**
       * <code>BALANCE_UPDATE_RES = 90;</code>
       */
      BALANCE_UPDATE_RES(90),
      /**
       * <code>ACCOUNT_CREATE_RES = 91;</code>
       */
      ACCOUNT_CREATE_RES(91),
      /**
       * <code>ACCOUNT_UPDATE_RES = 92;</code>
       */
      ACCOUNT_UPDATE_RES(92),
      /**
       * <code>ACCOUNT_DETAIL_RES = 93;</code>
       */
      ACCOUNT_DETAIL_RES(93),
      /**
       * <code>ACCOUNT_CREATE_MULTI_RES = 94;</code>
       */
      ACCOUNT_CREATE_MULTI_RES(94),
      /**
       * <code>ACCOUNT_BALANCE_RES = 95;</code>
       */
      ACCOUNT_BALANCE_RES(95),
      /**
       * <pre>
       *Querry message
       * </pre>
       *
       * <code>POSITION_REQ = 100;</code>
       */
      POSITION_REQ(100),
      /**
       * <code>ORDER_LIST_REQ = 101;</code>
       */
      ORDER_LIST_REQ(101),
      /**
       * <code>CONTRACT_LIST_REQ = 102;</code>
       */
      CONTRACT_LIST_REQ(102),
      /**
       * <code>SYMBOL_LIST_REQ = 103;</code>
       */
      SYMBOL_LIST_REQ(103),
      /**
       * <code>ORDER_DETAIL_REQ = 104;</code>
       */
      ORDER_DETAIL_REQ(104),
      /**
       * <code>SYMBOL_UPDATE_REQ = 105;</code>
       */
      SYMBOL_UPDATE_REQ(105),
      /**
       * <code>PORTFOLIO_LIST_REQ = 106;</code>
       */
      PORTFOLIO_LIST_REQ(106),
      /**
       * <code>POSITION_RES = 110;</code>
       */
      POSITION_RES(110),
      /**
       * <code>ORDER_LIST_RES = 111;</code>
       */
      ORDER_LIST_RES(111),
      /**
       * <code>CONTRACT_LIST_RES = 112;</code>
       */
      CONTRACT_LIST_RES(112),
      /**
       * <code>SYMBOL_LIST_RES = 113;</code>
       */
      SYMBOL_LIST_RES(113),
      /**
       * <code>ORDER_DETAIL_RES = 114;</code>
       */
      ORDER_DETAIL_RES(114),
      /**
       * <code>SYMBOL_UPDATE_RES = 115;</code>
       */
      SYMBOL_UPDATE_RES(115),
      /**
       * <code>PORTFOLIO_LIST_RES = 116;</code>
       */
      PORTFOLIO_LIST_RES(116),
      /**
       * <pre>
       *SPAN message
       * </pre>
       *
       * <code>SPAN_SIMULATE_REQ = 120;</code>
       */
      SPAN_SIMULATE_REQ(120),
      /**
       * <code>IMPORT_SPAN_PARAMETERS_REQ = 121;</code>
       */
      IMPORT_SPAN_PARAMETERS_REQ(121),
      /**
       * <code>SPAN_SIMULATE_RES = 130;</code>
       */
      SPAN_SIMULATE_RES(130),
      /**
       * <code>IMPORT_SPAN_PARAMETERS_RES = 131;</code>
       */
      IMPORT_SPAN_PARAMETERS_RES(131),
      /**
       * <code>PRICE_NOTI_SETTINGS_REQ = 140;</code>
       */
      PRICE_NOTI_SETTINGS_REQ(140),
      /**
       * <code>PRICE_NOTI_SETTINGS_RES = 141;</code>
       */
      PRICE_NOTI_SETTINGS_RES(141),
      /**
       * <code>ADMIN_EXECUTE_PREORDER_REQ = 1000;</code>
       */
      ADMIN_EXECUTE_PREORDER_REQ(1000),
      /**
       * <code>ADMIN_EXECUTE_PREORDER_RES = 1001;</code>
       */
      ADMIN_EXECUTE_PREORDER_RES(1001),
      /**
       * <code>ADMIN_BALANCE_UPDATE_REQ = 1002;</code>
       */
      ADMIN_BALANCE_UPDATE_REQ(1002),
      /**
       * <code>ADMIN_BALANCE_UPDATE_RES = 1003;</code>
       */
      ADMIN_BALANCE_UPDATE_RES(1003),
      /**
       * <code>ADMIN_GET_STOP_ORDER_LIST_REQ = 1004;</code>
       */
      ADMIN_GET_STOP_ORDER_LIST_REQ(1004),
      /**
       * <code>ADMIN_GET_STOP_ORDER_LIST_RES = 1005;</code>
       */
      ADMIN_GET_STOP_ORDER_LIST_RES(1005),
      /**
       * <code>ADMIN_EXPIRED_ORDER_REQ = 1006;</code>
       */
      ADMIN_EXPIRED_ORDER_REQ(1006),
      /**
       * <code>ADMIN_EXPIRED_ORDER_RES = 1007;</code>
       */
      ADMIN_EXPIRED_ORDER_RES(1007),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *Common message (0~19)
       * </pre>
       *
       * <code>PAYLOAD_NONE = 0;</code>
       */
      public static final int PAYLOAD_NONE_VALUE = 0;
      /**
       * <code>AUTHEN_REQ = 1;</code>
       */
      public static final int AUTHEN_REQ_VALUE = 1;
      /**
       * <code>HEARTBEAT_REQ = 2;</code>
       */
      public static final int HEARTBEAT_REQ_VALUE = 2;
      /**
       * <code>LOGIN_REQ = 3;</code>
       */
      public static final int LOGIN_REQ_VALUE = 3;
      /**
       * <code>AUTHEN_RES = 11;</code>
       */
      public static final int AUTHEN_RES_VALUE = 11;
      /**
       * <code>HEARTBEAT_RES = 12;</code>
       */
      public static final int HEARTBEAT_RES_VALUE = 12;
      /**
       * <code>LOGIN_RES = 13;</code>
       */
      public static final int LOGIN_RES_VALUE = 13;
      /**
       * <pre>
       *Pricing message (20~59)
       * </pre>
       *
       * <code>LAST_QUOTE_REQ = 20;</code>
       */
      public static final int LAST_QUOTE_REQ_VALUE = 20;
      /**
       * <code>SUBSCRIBE_QUOTE_REQ = 21;</code>
       */
      public static final int SUBSCRIBE_QUOTE_REQ_VALUE = 21;
      /**
       * <code>UNSUBSCRIBE_QUOTE_REQ = 22;</code>
       */
      public static final int UNSUBSCRIBE_QUOTE_REQ_VALUE = 22;
      /**
       * <code>CHART_REQ = 23;</code>
       */
      public static final int CHART_REQ_VALUE = 23;
      /**
       * <pre>
       *notify new quote to client
       * </pre>
       *
       * <code>QUOTE_EVENT = 29;</code>
       */
      public static final int QUOTE_EVENT_VALUE = 29;
      /**
       * <code>LAST_QUOTE_RES = 30;</code>
       */
      public static final int LAST_QUOTE_RES_VALUE = 30;
      /**
       * <code>SUBSCRIBE_QUOTE_RES = 31;</code>
       */
      public static final int SUBSCRIBE_QUOTE_RES_VALUE = 31;
      /**
       * <code>UNSUBSCRIBE_QUOTE_RES = 32;</code>
       */
      public static final int UNSUBSCRIBE_QUOTE_RES_VALUE = 32;
      /**
       * <code>CHART_RES = 33;</code>
       */
      public static final int CHART_RES_VALUE = 33;
      /**
       * <pre>
       *Trading messasge (60~99)
       * </pre>
       *
       * <code>NEW_ORDER_SINGLE_REQ = 60;</code>
       */
      public static final int NEW_ORDER_SINGLE_REQ_VALUE = 60;
      /**
       * <code>NEW_ORDER_MULTI_REQ = 61;</code>
       */
      public static final int NEW_ORDER_MULTI_REQ_VALUE = 61;
      /**
       * <code>CLOSE_ORDER_REQ = 62;</code>
       */
      public static final int CLOSE_ORDER_REQ_VALUE = 62;
      /**
       * <code>MODIFY_ORDER_REQ = 63;</code>
       */
      public static final int MODIFY_ORDER_REQ_VALUE = 63;
      /**
       * <code>CANCEL_ORDER_REQ = 64;</code>
       */
      public static final int CANCEL_ORDER_REQ_VALUE = 64;
      /**
       * <code>TRIGGERED_STOP_ORDER_REQ = 65;</code>
       */
      public static final int TRIGGERED_STOP_ORDER_REQ_VALUE = 65;
      /**
       * <pre>
       *notify position changed
       * </pre>
       *
       * <code>ORDER_EVENT = 68;</code>
       */
      public static final int ORDER_EVENT_VALUE = 68;
      /**
       * <code>NEW_ORDER_SINGLE_RES = 70;</code>
       */
      public static final int NEW_ORDER_SINGLE_RES_VALUE = 70;
      /**
       * <code>NEW_ORDER_MULTI_RES = 71;</code>
       */
      public static final int NEW_ORDER_MULTI_RES_VALUE = 71;
      /**
       * <code>CLOSE_ORDER_RES = 72;</code>
       */
      public static final int CLOSE_ORDER_RES_VALUE = 72;
      /**
       * <code>MODIFY_ORDER_RES = 73;</code>
       */
      public static final int MODIFY_ORDER_RES_VALUE = 73;
      /**
       * <code>CANCEL_ORDER_RES = 74;</code>
       */
      public static final int CANCEL_ORDER_RES_VALUE = 74;
      /**
       * <code>TRIGGERED_STOP_ORDER_RES = 75;</code>
       */
      public static final int TRIGGERED_STOP_ORDER_RES_VALUE = 75;
      /**
       * <pre>
       *Account
       * </pre>
       *
       * <code>BALANCE_UPDATE_REQ = 80;</code>
       */
      public static final int BALANCE_UPDATE_REQ_VALUE = 80;
      /**
       * <code>ACCOUNT_CREATE_REQ = 81;</code>
       */
      public static final int ACCOUNT_CREATE_REQ_VALUE = 81;
      /**
       * <code>ACCOUNT_UPDATE_REQ = 82;</code>
       */
      public static final int ACCOUNT_UPDATE_REQ_VALUE = 82;
      /**
       * <code>ACCOUNT_DETAIL_REQ = 83;</code>
       */
      public static final int ACCOUNT_DETAIL_REQ_VALUE = 83;
      /**
       * <code>ACCOUNT_CREATE_MULTI_REQ = 84;</code>
       */
      public static final int ACCOUNT_CREATE_MULTI_REQ_VALUE = 84;
      /**
       * <code>ACCOUNT_BALANCE_REQ = 85;</code>
       */
      public static final int ACCOUNT_BALANCE_REQ_VALUE = 85;
      /**
       * <code>BALANCE_UPDATE_RES = 90;</code>
       */
      public static final int BALANCE_UPDATE_RES_VALUE = 90;
      /**
       * <code>ACCOUNT_CREATE_RES = 91;</code>
       */
      public static final int ACCOUNT_CREATE_RES_VALUE = 91;
      /**
       * <code>ACCOUNT_UPDATE_RES = 92;</code>
       */
      public static final int ACCOUNT_UPDATE_RES_VALUE = 92;
      /**
       * <code>ACCOUNT_DETAIL_RES = 93;</code>
       */
      public static final int ACCOUNT_DETAIL_RES_VALUE = 93;
      /**
       * <code>ACCOUNT_CREATE_MULTI_RES = 94;</code>
       */
      public static final int ACCOUNT_CREATE_MULTI_RES_VALUE = 94;
      /**
       * <code>ACCOUNT_BALANCE_RES = 95;</code>
       */
      public static final int ACCOUNT_BALANCE_RES_VALUE = 95;
      /**
       * <pre>
       *Querry message
       * </pre>
       *
       * <code>POSITION_REQ = 100;</code>
       */
      public static final int POSITION_REQ_VALUE = 100;
      /**
       * <code>ORDER_LIST_REQ = 101;</code>
       */
      public static final int ORDER_LIST_REQ_VALUE = 101;
      /**
       * <code>CONTRACT_LIST_REQ = 102;</code>
       */
      public static final int CONTRACT_LIST_REQ_VALUE = 102;
      /**
       * <code>SYMBOL_LIST_REQ = 103;</code>
       */
      public static final int SYMBOL_LIST_REQ_VALUE = 103;
      /**
       * <code>ORDER_DETAIL_REQ = 104;</code>
       */
      public static final int ORDER_DETAIL_REQ_VALUE = 104;
      /**
       * <code>SYMBOL_UPDATE_REQ = 105;</code>
       */
      public static final int SYMBOL_UPDATE_REQ_VALUE = 105;
      /**
       * <code>PORTFOLIO_LIST_REQ = 106;</code>
       */
      public static final int PORTFOLIO_LIST_REQ_VALUE = 106;
      /**
       * <code>POSITION_RES = 110;</code>
       */
      public static final int POSITION_RES_VALUE = 110;
      /**
       * <code>ORDER_LIST_RES = 111;</code>
       */
      public static final int ORDER_LIST_RES_VALUE = 111;
      /**
       * <code>CONTRACT_LIST_RES = 112;</code>
       */
      public static final int CONTRACT_LIST_RES_VALUE = 112;
      /**
       * <code>SYMBOL_LIST_RES = 113;</code>
       */
      public static final int SYMBOL_LIST_RES_VALUE = 113;
      /**
       * <code>ORDER_DETAIL_RES = 114;</code>
       */
      public static final int ORDER_DETAIL_RES_VALUE = 114;
      /**
       * <code>SYMBOL_UPDATE_RES = 115;</code>
       */
      public static final int SYMBOL_UPDATE_RES_VALUE = 115;
      /**
       * <code>PORTFOLIO_LIST_RES = 116;</code>
       */
      public static final int PORTFOLIO_LIST_RES_VALUE = 116;
      /**
       * <pre>
       *SPAN message
       * </pre>
       *
       * <code>SPAN_SIMULATE_REQ = 120;</code>
       */
      public static final int SPAN_SIMULATE_REQ_VALUE = 120;
      /**
       * <code>IMPORT_SPAN_PARAMETERS_REQ = 121;</code>
       */
      public static final int IMPORT_SPAN_PARAMETERS_REQ_VALUE = 121;
      /**
       * <code>SPAN_SIMULATE_RES = 130;</code>
       */
      public static final int SPAN_SIMULATE_RES_VALUE = 130;
      /**
       * <code>IMPORT_SPAN_PARAMETERS_RES = 131;</code>
       */
      public static final int IMPORT_SPAN_PARAMETERS_RES_VALUE = 131;
      /**
       * <code>PRICE_NOTI_SETTINGS_REQ = 140;</code>
       */
      public static final int PRICE_NOTI_SETTINGS_REQ_VALUE = 140;
      /**
       * <code>PRICE_NOTI_SETTINGS_RES = 141;</code>
       */
      public static final int PRICE_NOTI_SETTINGS_RES_VALUE = 141;
      /**
       * <code>ADMIN_EXECUTE_PREORDER_REQ = 1000;</code>
       */
      public static final int ADMIN_EXECUTE_PREORDER_REQ_VALUE = 1000;
      /**
       * <code>ADMIN_EXECUTE_PREORDER_RES = 1001;</code>
       */
      public static final int ADMIN_EXECUTE_PREORDER_RES_VALUE = 1001;
      /**
       * <code>ADMIN_BALANCE_UPDATE_REQ = 1002;</code>
       */
      public static final int ADMIN_BALANCE_UPDATE_REQ_VALUE = 1002;
      /**
       * <code>ADMIN_BALANCE_UPDATE_RES = 1003;</code>
       */
      public static final int ADMIN_BALANCE_UPDATE_RES_VALUE = 1003;
      /**
       * <code>ADMIN_GET_STOP_ORDER_LIST_REQ = 1004;</code>
       */
      public static final int ADMIN_GET_STOP_ORDER_LIST_REQ_VALUE = 1004;
      /**
       * <code>ADMIN_GET_STOP_ORDER_LIST_RES = 1005;</code>
       */
      public static final int ADMIN_GET_STOP_ORDER_LIST_RES_VALUE = 1005;
      /**
       * <code>ADMIN_EXPIRED_ORDER_REQ = 1006;</code>
       */
      public static final int ADMIN_EXPIRED_ORDER_REQ_VALUE = 1006;
      /**
       * <code>ADMIN_EXPIRED_ORDER_RES = 1007;</code>
       */
      public static final int ADMIN_EXPIRED_ORDER_RES_VALUE = 1007;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static Payload valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Payload forNumber(int value) {
        switch (value) {
          case 0: return PAYLOAD_NONE;
          case 1: return AUTHEN_REQ;
          case 2: return HEARTBEAT_REQ;
          case 3: return LOGIN_REQ;
          case 11: return AUTHEN_RES;
          case 12: return HEARTBEAT_RES;
          case 13: return LOGIN_RES;
          case 20: return LAST_QUOTE_REQ;
          case 21: return SUBSCRIBE_QUOTE_REQ;
          case 22: return UNSUBSCRIBE_QUOTE_REQ;
          case 23: return CHART_REQ;
          case 29: return QUOTE_EVENT;
          case 30: return LAST_QUOTE_RES;
          case 31: return SUBSCRIBE_QUOTE_RES;
          case 32: return UNSUBSCRIBE_QUOTE_RES;
          case 33: return CHART_RES;
          case 60: return NEW_ORDER_SINGLE_REQ;
          case 61: return NEW_ORDER_MULTI_REQ;
          case 62: return CLOSE_ORDER_REQ;
          case 63: return MODIFY_ORDER_REQ;
          case 64: return CANCEL_ORDER_REQ;
          case 65: return TRIGGERED_STOP_ORDER_REQ;
          case 68: return ORDER_EVENT;
          case 70: return NEW_ORDER_SINGLE_RES;
          case 71: return NEW_ORDER_MULTI_RES;
          case 72: return CLOSE_ORDER_RES;
          case 73: return MODIFY_ORDER_RES;
          case 74: return CANCEL_ORDER_RES;
          case 75: return TRIGGERED_STOP_ORDER_RES;
          case 80: return BALANCE_UPDATE_REQ;
          case 81: return ACCOUNT_CREATE_REQ;
          case 82: return ACCOUNT_UPDATE_REQ;
          case 83: return ACCOUNT_DETAIL_REQ;
          case 84: return ACCOUNT_CREATE_MULTI_REQ;
          case 85: return ACCOUNT_BALANCE_REQ;
          case 90: return BALANCE_UPDATE_RES;
          case 91: return ACCOUNT_CREATE_RES;
          case 92: return ACCOUNT_UPDATE_RES;
          case 93: return ACCOUNT_DETAIL_RES;
          case 94: return ACCOUNT_CREATE_MULTI_RES;
          case 95: return ACCOUNT_BALANCE_RES;
          case 100: return POSITION_REQ;
          case 101: return ORDER_LIST_REQ;
          case 102: return CONTRACT_LIST_REQ;
          case 103: return SYMBOL_LIST_REQ;
          case 104: return ORDER_DETAIL_REQ;
          case 105: return SYMBOL_UPDATE_REQ;
          case 106: return PORTFOLIO_LIST_REQ;
          case 110: return POSITION_RES;
          case 111: return ORDER_LIST_RES;
          case 112: return CONTRACT_LIST_RES;
          case 113: return SYMBOL_LIST_RES;
          case 114: return ORDER_DETAIL_RES;
          case 115: return SYMBOL_UPDATE_RES;
          case 116: return PORTFOLIO_LIST_RES;
          case 120: return SPAN_SIMULATE_REQ;
          case 121: return IMPORT_SPAN_PARAMETERS_REQ;
          case 130: return SPAN_SIMULATE_RES;
          case 131: return IMPORT_SPAN_PARAMETERS_RES;
          case 140: return PRICE_NOTI_SETTINGS_REQ;
          case 141: return PRICE_NOTI_SETTINGS_RES;
          case 1000: return ADMIN_EXECUTE_PREORDER_REQ;
          case 1001: return ADMIN_EXECUTE_PREORDER_RES;
          case 1002: return ADMIN_BALANCE_UPDATE_REQ;
          case 1003: return ADMIN_BALANCE_UPDATE_RES;
          case 1004: return ADMIN_GET_STOP_ORDER_LIST_REQ;
          case 1005: return ADMIN_GET_STOP_ORDER_LIST_RES;
          case 1006: return ADMIN_EXPIRED_ORDER_REQ;
          case 1007: return ADMIN_EXPIRED_ORDER_RES;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Payload>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Payload> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Payload>() {
              public Payload findValueByNumber(int number) {
                return Payload.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RpcMessage.getDescriptor().getEnumTypes().get(2);
      }

      private static final Payload[] VALUES = values();

      public static Payload valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Payload(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RpcMessage.Payload)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <pre>
     * </pre>
     *
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @Override
    public long getId() {
      return id_;
    }

    public static final int RESULT_FIELD_NUMBER = 2;
    private int result_;
    /**
     * <code>.RpcMessage.Result result = 2;</code>
     * @return The enum numeric value on the wire for result.
     */
    @Override public int getResultValue() {
      return result_;
    }
    /**
     * <code>.RpcMessage.Result result = 2;</code>
     * @return The result.
     */
    @Override public Result getResult() {
      @SuppressWarnings("deprecation")
      Result result = Result.valueOf(result_);
      return result == null ? Result.UNRECOGNIZED : result;
    }

    public static final int VERSION_FIELD_NUMBER = 3;
    private volatile Object version_;
    /**
     * <code>string version = 3;</code>
     * @return The version.
     */
    @Override
    public String getVersion() {
      Object ref = version_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 3;</code>
     * @return The bytes for version.
     */
    @Override
    public com.google.protobuf.ByteString
        getVersionBytes() {
      Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVICE_FIELD_NUMBER = 4;
    private volatile Object service_;
    /**
     * <code>string service = 4;</code>
     * @return The service.
     */
    @Override
    public String getService() {
      Object ref = service_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        service_ = s;
        return s;
      }
    }
    /**
     * <code>string service = 4;</code>
     * @return The bytes for service.
     */
    @Override
    public com.google.protobuf.ByteString
        getServiceBytes() {
      Object ref = service_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        service_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_FIELD_NUMBER = 5;
    private int source_;
    /**
     * <code>.RpcMessage.Source source = 5;</code>
     * @return The enum numeric value on the wire for source.
     */
    @Override public int getSourceValue() {
      return source_;
    }
    /**
     * <code>.RpcMessage.Source source = 5;</code>
     * @return The source.
     */
    @Override public Source getSource() {
      @SuppressWarnings("deprecation")
      Source result = Source.valueOf(source_);
      return result == null ? Source.UNRECOGNIZED : result;
    }

    public static final int CONTEXT_ID_FIELD_NUMBER = 6;
    private long contextId_;
    /**
     * <code>int64 context_id = 6;</code>
     * @return The contextId.
     */
    @Override
    public long getContextId() {
      return contextId_;
    }

    public static final int PAYLOAD_DATA_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString payloadData_;
    /**
     * <code>bytes payload_data = 7;</code>
     * @return The payloadData.
     */
    @Override
    public com.google.protobuf.ByteString getPayloadData() {
      return payloadData_;
    }

    public static final int PAYLOAD_CLASS_FIELD_NUMBER = 8;
    private int payloadClass_;
    /**
     * <code>.RpcMessage.Payload payload_class = 8;</code>
     * @return The enum numeric value on the wire for payloadClass.
     */
    @Override public int getPayloadClassValue() {
      return payloadClass_;
    }
    /**
     * <code>.RpcMessage.Payload payload_class = 8;</code>
     * @return The payloadClass.
     */
    @Override public Payload getPayloadClass() {
      @SuppressWarnings("deprecation")
      Payload result = Payload.valueOf(payloadClass_);
      return result == null ? Payload.UNRECOGNIZED : result;
    }

    public static final int COMPRESS_FIELD_NUMBER = 10;
    private boolean compress_;
    /**
     * <code>bool compress = 10;</code>
     * @return The compress.
     */
    @Override
    public boolean getCompress() {
      return compress_;
    }

    public static final int PAGING_FIELD_NUMBER = 11;
    private long paging_;
    /**
     * <code>int64 paging = 11;</code>
     * @return The paging.
     */
    @Override
    public long getPaging() {
      return paging_;
    }

    public static final int LIMIT_FIELD_NUMBER = 12;
    private long limit_;
    /**
     * <code>int64 limit = 12;</code>
     * @return The limit.
     */
    @Override
    public long getLimit() {
      return limit_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (result_ != Result.RESULT_NONE.getNumber()) {
        output.writeEnum(2, result_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, version_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, service_);
      }
      if (source_ != Source.SOURCE_NONE.getNumber()) {
        output.writeEnum(5, source_);
      }
      if (contextId_ != 0L) {
        output.writeInt64(6, contextId_);
      }
      if (!payloadData_.isEmpty()) {
        output.writeBytes(7, payloadData_);
      }
      if (payloadClass_ != Payload.PAYLOAD_NONE.getNumber()) {
        output.writeEnum(8, payloadClass_);
      }
      if (compress_ != false) {
        output.writeBool(10, compress_);
      }
      if (paging_ != 0L) {
        output.writeInt64(11, paging_);
      }
      if (limit_ != 0L) {
        output.writeInt64(12, limit_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (result_ != Result.RESULT_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, result_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(version_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, version_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(service_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, service_);
      }
      if (source_ != Source.SOURCE_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, source_);
      }
      if (contextId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, contextId_);
      }
      if (!payloadData_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, payloadData_);
      }
      if (payloadClass_ != Payload.PAYLOAD_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, payloadClass_);
      }
      if (compress_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, compress_);
      }
      if (paging_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, paging_);
      }
      if (limit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, limit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RpcMessage)) {
        return super.equals(obj);
      }
      RpcMessage other = (RpcMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (result_ != other.result_) return false;
      if (!getVersion()
          .equals(other.getVersion())) return false;
      if (!getService()
          .equals(other.getService())) return false;
      if (source_ != other.source_) return false;
      if (getContextId()
          != other.getContextId()) return false;
      if (!getPayloadData()
          .equals(other.getPayloadData())) return false;
      if (payloadClass_ != other.payloadClass_) return false;
      if (getCompress()
          != other.getCompress()) return false;
      if (getPaging()
          != other.getPaging()) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + result_;
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + SERVICE_FIELD_NUMBER;
      hash = (53 * hash) + getService().hashCode();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + source_;
      hash = (37 * hash) + CONTEXT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getContextId());
      hash = (37 * hash) + PAYLOAD_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadData().hashCode();
      hash = (37 * hash) + PAYLOAD_CLASS_FIELD_NUMBER;
      hash = (53 * hash) + payloadClass_;
      hash = (37 * hash) + COMPRESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getCompress());
      hash = (37 * hash) + PAGING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPaging());
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLimit());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RpcMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RpcMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RpcMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RpcMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RpcMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RpcMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code RpcMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RpcMessage)
        RpcMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Rpc.internal_static_RpcMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Rpc.internal_static_RpcMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RpcMessage.class, Builder.class);
      }

      // Construct using Rpc.RpcMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        result_ = 0;

        version_ = "";

        service_ = "";

        source_ = 0;

        contextId_ = 0L;

        payloadData_ = com.google.protobuf.ByteString.EMPTY;

        payloadClass_ = 0;

        compress_ = false;

        paging_ = 0L;

        limit_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Rpc.internal_static_RpcMessage_descriptor;
      }

      @Override
      public RpcMessage getDefaultInstanceForType() {
        return RpcMessage.getDefaultInstance();
      }

      @Override
      public RpcMessage build() {
        RpcMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RpcMessage buildPartial() {
        RpcMessage result = new RpcMessage(this);
        result.id_ = id_;
        result.result_ = result_;
        result.version_ = version_;
        result.service_ = service_;
        result.source_ = source_;
        result.contextId_ = contextId_;
        result.payloadData_ = payloadData_;
        result.payloadClass_ = payloadClass_;
        result.compress_ = compress_;
        result.paging_ = paging_;
        result.limit_ = limit_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RpcMessage) {
          return mergeFrom((RpcMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RpcMessage other) {
        if (other == RpcMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.result_ != 0) {
          setResultValue(other.getResultValue());
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (!other.getService().isEmpty()) {
          service_ = other.service_;
          onChanged();
        }
        if (other.source_ != 0) {
          setSourceValue(other.getSourceValue());
        }
        if (other.getContextId() != 0L) {
          setContextId(other.getContextId());
        }
        if (other.getPayloadData() != com.google.protobuf.ByteString.EMPTY) {
          setPayloadData(other.getPayloadData());
        }
        if (other.payloadClass_ != 0) {
          setPayloadClassValue(other.getPayloadClassValue());
        }
        if (other.getCompress() != false) {
          setCompress(other.getCompress());
        }
        if (other.getPaging() != 0L) {
          setPaging(other.getPaging());
        }
        if (other.getLimit() != 0L) {
          setLimit(other.getLimit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RpcMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RpcMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return The id.
       */
      @Override
      public long getId() {
        return id_;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>int64 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int result_ = 0;
      /**
       * <code>.RpcMessage.Result result = 2;</code>
       * @return The enum numeric value on the wire for result.
       */
      @Override public int getResultValue() {
        return result_;
      }
      /**
       * <code>.RpcMessage.Result result = 2;</code>
       * @param value The enum numeric value on the wire for result to set.
       * @return This builder for chaining.
       */
      public Builder setResultValue(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RpcMessage.Result result = 2;</code>
       * @return The result.
       */
      @Override
      public Result getResult() {
        @SuppressWarnings("deprecation")
        Result result = Result.valueOf(result_);
        return result == null ? Result.UNRECOGNIZED : result;
      }
      /**
       * <code>.RpcMessage.Result result = 2;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RpcMessage.Result result = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private Object version_ = "";
      /**
       * <code>string version = 3;</code>
       * @return The version.
       */
      public String getVersion() {
        Object ref = version_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string version = 3;</code>
       * @return The bytes for version.
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 3;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 3;</code>
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private Object service_ = "";
      /**
       * <code>string service = 4;</code>
       * @return The service.
       */
      public String getService() {
        Object ref = service_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          service_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string service = 4;</code>
       * @return The bytes for service.
       */
      public com.google.protobuf.ByteString
          getServiceBytes() {
        Object ref = service_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          service_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string service = 4;</code>
       * @param value The service to set.
       * @return This builder for chaining.
       */
      public Builder setService(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        service_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string service = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearService() {
        
        service_ = getDefaultInstance().getService();
        onChanged();
        return this;
      }
      /**
       * <code>string service = 4;</code>
       * @param value The bytes for service to set.
       * @return This builder for chaining.
       */
      public Builder setServiceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        service_ = value;
        onChanged();
        return this;
      }

      private int source_ = 0;
      /**
       * <code>.RpcMessage.Source source = 5;</code>
       * @return The enum numeric value on the wire for source.
       */
      @Override public int getSourceValue() {
        return source_;
      }
      /**
       * <code>.RpcMessage.Source source = 5;</code>
       * @param value The enum numeric value on the wire for source to set.
       * @return This builder for chaining.
       */
      public Builder setSourceValue(int value) {
        
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RpcMessage.Source source = 5;</code>
       * @return The source.
       */
      @Override
      public Source getSource() {
        @SuppressWarnings("deprecation")
        Source result = Source.valueOf(source_);
        return result == null ? Source.UNRECOGNIZED : result;
      }
      /**
       * <code>.RpcMessage.Source source = 5;</code>
       * @param value The source to set.
       * @return This builder for chaining.
       */
      public Builder setSource(Source value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        source_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RpcMessage.Source source = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSource() {
        
        source_ = 0;
        onChanged();
        return this;
      }

      private long contextId_ ;
      /**
       * <code>int64 context_id = 6;</code>
       * @return The contextId.
       */
      @Override
      public long getContextId() {
        return contextId_;
      }
      /**
       * <code>int64 context_id = 6;</code>
       * @param value The contextId to set.
       * @return This builder for chaining.
       */
      public Builder setContextId(long value) {
        
        contextId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 context_id = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContextId() {
        
        contextId_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payloadData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload_data = 7;</code>
       * @return The payloadData.
       */
      @Override
      public com.google.protobuf.ByteString getPayloadData() {
        return payloadData_;
      }
      /**
       * <code>bytes payload_data = 7;</code>
       * @param value The payloadData to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payloadData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload_data = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayloadData() {
        
        payloadData_ = getDefaultInstance().getPayloadData();
        onChanged();
        return this;
      }

      private int payloadClass_ = 0;
      /**
       * <code>.RpcMessage.Payload payload_class = 8;</code>
       * @return The enum numeric value on the wire for payloadClass.
       */
      @Override public int getPayloadClassValue() {
        return payloadClass_;
      }
      /**
       * <code>.RpcMessage.Payload payload_class = 8;</code>
       * @param value The enum numeric value on the wire for payloadClass to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadClassValue(int value) {
        
        payloadClass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RpcMessage.Payload payload_class = 8;</code>
       * @return The payloadClass.
       */
      @Override
      public Payload getPayloadClass() {
        @SuppressWarnings("deprecation")
        Payload result = Payload.valueOf(payloadClass_);
        return result == null ? Payload.UNRECOGNIZED : result;
      }
      /**
       * <code>.RpcMessage.Payload payload_class = 8;</code>
       * @param value The payloadClass to set.
       * @return This builder for chaining.
       */
      public Builder setPayloadClass(Payload value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        payloadClass_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RpcMessage.Payload payload_class = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPayloadClass() {
        
        payloadClass_ = 0;
        onChanged();
        return this;
      }

      private boolean compress_ ;
      /**
       * <code>bool compress = 10;</code>
       * @return The compress.
       */
      @Override
      public boolean getCompress() {
        return compress_;
      }
      /**
       * <code>bool compress = 10;</code>
       * @param value The compress to set.
       * @return This builder for chaining.
       */
      public Builder setCompress(boolean value) {
        
        compress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool compress = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearCompress() {
        
        compress_ = false;
        onChanged();
        return this;
      }

      private long paging_ ;
      /**
       * <code>int64 paging = 11;</code>
       * @return The paging.
       */
      @Override
      public long getPaging() {
        return paging_;
      }
      /**
       * <code>int64 paging = 11;</code>
       * @param value The paging to set.
       * @return This builder for chaining.
       */
      public Builder setPaging(long value) {
        
        paging_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 paging = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearPaging() {
        
        paging_ = 0L;
        onChanged();
        return this;
      }

      private long limit_ ;
      /**
       * <code>int64 limit = 12;</code>
       * @return The limit.
       */
      @Override
      public long getLimit() {
        return limit_;
      }
      /**
       * <code>int64 limit = 12;</code>
       * @param value The limit to set.
       * @return This builder for chaining.
       */
      public Builder setLimit(long value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 limit = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearLimit() {
        
        limit_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RpcMessage)
    }

    // @@protoc_insertion_point(class_scope:RpcMessage)
    private static final RpcMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RpcMessage();
    }

    public static RpcMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RpcMessage>
        PARSER = new com.google.protobuf.AbstractParser<RpcMessage>() {
      @Override
      public RpcMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RpcMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RpcMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RpcMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public RpcMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RpcMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RpcMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\trpc.proto\"\315\021\n\nRpcMessage\022\n\n\002id\030\001 \001(\003\022\"" +
      "\n\006result\030\002 \001(\0162\022.RpcMessage.Result\022\017\n\007ve" +
      "rsion\030\003 \001(\t\022\017\n\007service\030\004 \001(\t\022\"\n\006source\030\005" +
      " \001(\0162\022.RpcMessage.Source\022\022\n\ncontext_id\030\006" +
      " \001(\003\022\024\n\014payload_data\030\007 \001(\014\022*\n\rpayload_cl" +
      "ass\030\010 \001(\0162\023.RpcMessage.Payload\022\020\n\010compre" +
      "ss\030\n \001(\010\022\016\n\006paging\030\013 \001(\003\022\r\n\005limit\030\014 \001(\003\"" +
      "\367\001\n\006Result\022\017\n\013RESULT_NONE\020\000\022\023\n\017INVALID_V" +
      "ERSION\020\002\022\023\n\017INVALID_SERVICE\020\003\022\023\n\017INVALID" +
      "_PAYLOAD\020\004\022\025\n\021NOT_AUTHENTICATED\020\005\022\023\n\017SER" +
      "VICE_TIMEOUT\020\006\022\024\n\020SERVICE_REJECTED\020\007\022\027\n\023" +
      "SERVICE_UNAVAILABLE\020\010\022\017\n\013REQUIRE_VPN\020\t\022\020" +
      "\n\014MAINTAINANCE\020\n\022\022\n\016INTERNAL_ERROR\020c\022\013\n\007" +
      "SUCCESS\020d\"F\n\006Source\022\017\n\013SOURCE_NONE\020\000\022\007\n\003" +
      "IOS\020\001\022\013\n\007ANDROID\020\002\022\014\n\010External\020\t\022\007\n\003WEB\020" +
      "\n\"\377\014\n\007Payload\022\020\n\014PAYLOAD_NONE\020\000\022\016\n\nAUTHE" +
      "N_REQ\020\001\022\021\n\rHEARTBEAT_REQ\020\002\022\r\n\tLOGIN_REQ\020" +
      "\003\022\016\n\nAUTHEN_RES\020\013\022\021\n\rHEARTBEAT_RES\020\014\022\r\n\t" +
      "LOGIN_RES\020\r\022\022\n\016LAST_QUOTE_REQ\020\024\022\027\n\023SUBSC" +
      "RIBE_QUOTE_REQ\020\025\022\031\n\025UNSUBSCRIBE_QUOTE_RE" +
      "Q\020\026\022\r\n\tCHART_REQ\020\027\022\017\n\013QUOTE_EVENT\020\035\022\022\n\016L" +
      "AST_QUOTE_RES\020\036\022\027\n\023SUBSCRIBE_QUOTE_RES\020\037" +
      "\022\031\n\025UNSUBSCRIBE_QUOTE_RES\020 \022\r\n\tCHART_RES" +
      "\020!\022\030\n\024NEW_ORDER_SINGLE_REQ\020<\022\027\n\023NEW_ORDE" +
      "R_MULTI_REQ\020=\022\023\n\017CLOSE_ORDER_REQ\020>\022\024\n\020MO" +
      "DIFY_ORDER_REQ\020?\022\024\n\020CANCEL_ORDER_REQ\020@\022\034" +
      "\n\030TRIGGERED_STOP_ORDER_REQ\020A\022\017\n\013ORDER_EV" +
      "ENT\020D\022\030\n\024NEW_ORDER_SINGLE_RES\020F\022\027\n\023NEW_O" +
      "RDER_MULTI_RES\020G\022\023\n\017CLOSE_ORDER_RES\020H\022\024\n" +
      "\020MODIFY_ORDER_RES\020I\022\024\n\020CANCEL_ORDER_RES\020" +
      "J\022\034\n\030TRIGGERED_STOP_ORDER_RES\020K\022\026\n\022BALAN" +
      "CE_UPDATE_REQ\020P\022\026\n\022ACCOUNT_CREATE_REQ\020Q\022" +
      "\026\n\022ACCOUNT_UPDATE_REQ\020R\022\026\n\022ACCOUNT_DETAI" +
      "L_REQ\020S\022\034\n\030ACCOUNT_CREATE_MULTI_REQ\020T\022\027\n" +
      "\023ACCOUNT_BALANCE_REQ\020U\022\026\n\022BALANCE_UPDATE" +
      "_RES\020Z\022\026\n\022ACCOUNT_CREATE_RES\020[\022\026\n\022ACCOUN" +
      "T_UPDATE_RES\020\\\022\026\n\022ACCOUNT_DETAIL_RES\020]\022\034" +
      "\n\030ACCOUNT_CREATE_MULTI_RES\020^\022\027\n\023ACCOUNT_" +
      "BALANCE_RES\020_\022\020\n\014POSITION_REQ\020d\022\022\n\016ORDER" +
      "_LIST_REQ\020e\022\025\n\021CONTRACT_LIST_REQ\020f\022\023\n\017SY" +
      "MBOL_LIST_REQ\020g\022\024\n\020ORDER_DETAIL_REQ\020h\022\025\n" +
      "\021SYMBOL_UPDATE_REQ\020i\022\026\n\022PORTFOLIO_LIST_R" +
      "EQ\020j\022\020\n\014POSITION_RES\020n\022\022\n\016ORDER_LIST_RES" +
      "\020o\022\025\n\021CONTRACT_LIST_RES\020p\022\023\n\017SYMBOL_LIST" +
      "_RES\020q\022\024\n\020ORDER_DETAIL_RES\020r\022\025\n\021SYMBOL_U" +
      "PDATE_RES\020s\022\026\n\022PORTFOLIO_LIST_RES\020t\022\025\n\021S" +
      "PAN_SIMULATE_REQ\020x\022\036\n\032IMPORT_SPAN_PARAME" +
      "TERS_REQ\020y\022\026\n\021SPAN_SIMULATE_RES\020\202\001\022\037\n\032IM" +
      "PORT_SPAN_PARAMETERS_RES\020\203\001\022\034\n\027PRICE_NOT" +
      "I_SETTINGS_REQ\020\214\001\022\034\n\027PRICE_NOTI_SETTINGS" +
      "_RES\020\215\001\022\037\n\032ADMIN_EXECUTE_PREORDER_REQ\020\350\007" +
      "\022\037\n\032ADMIN_EXECUTE_PREORDER_RES\020\351\007\022\035\n\030ADM" +
      "IN_BALANCE_UPDATE_REQ\020\352\007\022\035\n\030ADMIN_BALANC" +
      "E_UPDATE_RES\020\353\007\022\"\n\035ADMIN_GET_STOP_ORDER_" +
      "LIST_REQ\020\354\007\022\"\n\035ADMIN_GET_STOP_ORDER_LIST" +
      "_RES\020\355\007\022\034\n\027ADMIN_EXPIRED_ORDER_REQ\020\356\007\022\034\n" +
      "\027ADMIN_EXPIRED_ORDER_RES\020\357\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RpcMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RpcMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RpcMessage_descriptor,
        new String[] { "Id", "Result", "Version", "Service", "Source", "ContextId", "PayloadData", "PayloadClass", "Compress", "Paging", "Limit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
